/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.EnderecoDAO;
import control.UsuarioFornecedorDAO;
import control.UsuarioRecebedorDAO;
import javax.swing.JFormattedTextField;
import javax.swing.text.MaskFormatter;
import model.Endereco;
import model.UsuarioFornecedor;
import model.UsuarioRecebedor;

/**
 *
 * @author edu_a
 */
public class TelaDeCadastro extends javax.swing.JFrame {

    /**
     * Creates new form telaDeCadastro
     */
    public TelaDeCadastro() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        campoNomeTelaCadastro = new javax.swing.JTextField();
        campoEmailTelaCadastro = new javax.swing.JTextField();
        campoRuaTelaCadastro = new javax.swing.JTextField();
        campoNumeroTelaCadastro = new javax.swing.JTextField();
        campoBairroTelaCadastro = new javax.swing.JTextField();
        campoSenhaTelaCadastro = new javax.swing.JPasswordField();
        RadioButtonFornecedorCadastro = new javax.swing.JRadioButton();
        RadioButtonRecebedorCadastro = new javax.swing.JRadioButton();
        botaoCadastrar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        campoCepTelaCadastro = new javax.swing.JFormattedTextField();
        campoTelefoneTelaCadastro = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        campoCidadeTelaCadastro = new javax.swing.JTextField();
        campoEstadoTelaCadastro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NOME");

        jLabel2.setText("EMAIL");

        jLabel3.setText("TELEFONE");

        jLabel4.setText("SENHA");

        jLabel5.setText("ENDEREÇO:");

        jLabel6.setText("RUA");

        jLabel7.setText("NUMERO");

        jLabel8.setText("BAIRRO");

        jLabel9.setText("CEP");

        campoNomeTelaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeTelaCadastroActionPerformed(evt);
            }
        });

        campoEmailTelaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEmailTelaCadastroActionPerformed(evt);
            }
        });

        campoRuaTelaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoRuaTelaCadastroActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadioButtonFornecedorCadastro);
        RadioButtonFornecedorCadastro.setText("FORNECEDOR");
        RadioButtonFornecedorCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonFornecedorCadastroActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadioButtonRecebedorCadastro);
        RadioButtonRecebedorCadastro.setText("RECEBEDOR");
        RadioButtonRecebedorCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonRecebedorCadastroActionPerformed(evt);
            }
        });

        botaoCadastrar.setText("CADASTRAR");
        botaoCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCadastrarMouseClicked(evt);
            }
        });
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        try {
            campoCepTelaCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoCepTelaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCepTelaCadastroActionPerformed(evt);
            }
        });

        try {
            campoTelefoneTelaCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel10.setText("ESTADO");

        jLabel11.setText("CIDADE");

        campoEstadoTelaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEstadoTelaCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(botaoCadastrar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoRuaTelaCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                    .addComponent(campoNumeroTelaCadastro)
                                    .addComponent(campoBairroTelaCadastro))))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                .addComponent(campoCepTelaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoEstadoTelaCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(campoCidadeTelaCadastro)))))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadioButtonFornecedorCadastro)
                            .addComponent(RadioButtonRecebedorCadastro)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoEmailTelaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoNomeTelaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoSenhaTelaCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                    .addComponent(campoTelefoneTelaCadastro))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(174, 174, 174))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RadioButtonFornecedorCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RadioButtonRecebedorCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoNomeTelaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoEmailTelaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoTelefoneTelaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoSenhaTelaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(campoRuaTelaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(campoEstadoTelaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(campoNumeroTelaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(campoCidadeTelaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(campoBairroTelaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCepTelaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(32, 32, 32)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(botaoCadastrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        if (RadioButtonFornecedorCadastro.isSelected()) {
            
            UsuarioFornecedor uf = new UsuarioFornecedor();
            UsuarioFornecedorDAO ufd = new UsuarioFornecedorDAO();
            
            Endereco endereco = new Endereco();
            EnderecoDAO ed = new EnderecoDAO();
            
           // UsuarioRecebedor ur = new UsuarioRecebedor();

            uf.setPontuacao(0);

            uf.setNome(campoNomeTelaCadastro.getText());

            uf.setEmail(campoEmailTelaCadastro.getText());

            uf.setSenha(String.valueOf(campoSenhaTelaCadastro.getPassword()));
            
            endereco.setEmailFornecedor(campoEmailTelaCadastro.getText());

            endereco.setRua(campoRuaTelaCadastro.getText());

            endereco.setNumero(Integer.parseInt(campoNumeroTelaCadastro.getText()));

            endereco.setBairro(campoBairroTelaCadastro.getText());
            
            endereco.setCidade(campoCidadeTelaCadastro.getText());
            
            endereco.setEstado(campoEstadoTelaCadastro.getText());

            endereco.setCep(campoCepTelaCadastro.getText());

            uf.setEndereco(endereco);

            uf.setTelefone(campoTelefoneTelaCadastro.getText());

            uf.setFuncao(1);
            
            ufd.cadastrarUsuarioFornecedor(uf);
            
            ed.cadastrarEndereco(endereco);
            
            
            
            

           
        }else if(RadioButtonRecebedorCadastro.isSelected()){
            
            UsuarioRecebedor ur = new UsuarioRecebedor();
            UsuarioRecebedorDAO urd = new UsuarioRecebedorDAO();
            
            Endereco endereco = new Endereco();
            EnderecoDAO ed = new EnderecoDAO();
            
            //UsuarioFornecedor uf = new UsuarioFornecedor();
            
            ur.setNivel(0);

            ur.setNome(campoNomeTelaCadastro.getText());

            ur.setEmail(campoEmailTelaCadastro.getText());

            ur.setSenha(String.valueOf(campoSenhaTelaCadastro.getPassword()));
            
            endereco.setEmailRecebedor(campoEmailTelaCadastro.getText());

            endereco.setRua(campoRuaTelaCadastro.getText());

            endereco.setNumero(Integer.parseInt(campoNumeroTelaCadastro.getText()));

            endereco.setBairro(campoBairroTelaCadastro.getText());

            endereco.setCep(campoCepTelaCadastro.getText());

            ur.setEndereco(endereco);

            ur.setTelefone(campoTelefoneTelaCadastro.getText());
            
            ur.setFuncao(2);
            
            urd.cadastrarUsuarioRecebedor(ur);
            
            ed.cadastrarEndereco(endereco);
            
            
            
            
        }

        this.dispose();
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void RadioButtonFornecedorCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonFornecedorCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonFornecedorCadastroActionPerformed

    private void campoRuaTelaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoRuaTelaCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoRuaTelaCadastroActionPerformed

    private void campoEmailTelaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEmailTelaCadastroActionPerformed

    }//GEN-LAST:event_campoEmailTelaCadastroActionPerformed

    private void botaoCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCadastrarMouseClicked

    }//GEN-LAST:event_botaoCadastrarMouseClicked

    private void RadioButtonRecebedorCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonRecebedorCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonRecebedorCadastroActionPerformed

    private void campoNomeTelaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeTelaCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeTelaCadastroActionPerformed

    private void campoCepTelaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCepTelaCadastroActionPerformed
           
    }//GEN-LAST:event_campoCepTelaCadastroActionPerformed

    private void campoEstadoTelaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEstadoTelaCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEstadoTelaCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioButtonFornecedorCadastro;
    private javax.swing.JRadioButton RadioButtonRecebedorCadastro;
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField campoBairroTelaCadastro;
    private javax.swing.JFormattedTextField campoCepTelaCadastro;
    private javax.swing.JTextField campoCidadeTelaCadastro;
    private javax.swing.JTextField campoEmailTelaCadastro;
    private javax.swing.JTextField campoEstadoTelaCadastro;
    private javax.swing.JTextField campoNomeTelaCadastro;
    private javax.swing.JTextField campoNumeroTelaCadastro;
    private javax.swing.JTextField campoRuaTelaCadastro;
    private javax.swing.JPasswordField campoSenhaTelaCadastro;
    private javax.swing.JFormattedTextField campoTelefoneTelaCadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
