package view;

import control.MissaoDao;
import control.UsuarioFornecedorDAO;
import control.UsuarioRecebedorDAO;
import javax.swing.DefaultListModel;
import javax.swing.JSpinner;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import model.Material;
import model.Missao;
import model.Status;
import view.model.LoginModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author edu_a
 */
public class TelaUsuarioRecebedor extends javax.swing.JFrame {

    /**
     * Creates new form TelaUsuarioRecebedor
     */
   
   
    
    

    public TelaUsuarioRecebedor() {

        initComponents();
        this.setLocationRelativeTo(null);
        
        //jSpinnerQtdMaterial.setValue(1);
        //SpinnerNumberModel nm = new SpinnerNumberModel();
        //nm.setMinimum(1);
        //nm.setStepSize(1);
        //jSpinnerQtdMaterial.setModel(nm);
    }
       
    public void receberEmail(LoginModel model){
        jLabelEmail.setText(model.getEmail());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        TelaRecebedorMenuMissao = new javax.swing.JTabbedPane();
        jPanelCriarMissao = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        RadioMaterialBorracha = new javax.swing.JRadioButton();
        RadioMaterialVidro = new javax.swing.JRadioButton();
        RadioMaterialMetais = new javax.swing.JRadioButton();
        RadioMaterialMadeira = new javax.swing.JRadioButton();
        RadioMaterialPlastico = new javax.swing.JRadioButton();
        RadioMaterialPapel = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        TelaRecebedorNomeMissao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TelaRecebedorMenuObjetivoMissao = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jSpinnerQtdMaterial = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        TelaRecebedorPontuacaoMissaoCriada = new javax.swing.JLabel();
        CadastrarMissao = new javax.swing.JToggleButton();
        jPanelEmAberto = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListaDeMissaoEmAberto = new javax.swing.JList<>();
        jButtonAtualizarListaEmAberto = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanelEmAndamento = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TelaRecebedorMissoesEmAndamento = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        BotaoConcluirMissaoEmAndamento = new javax.swing.JButton();
        BotaoMissaoNaoConcluida = new javax.swing.JButton();
        jButtonAtualizarListaEmAndamento = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanelConcluida = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ListaMissoesConcluidas = new javax.swing.JList<>();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jButtonAtualizarListaMissoesConcluidas = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jListMissoesNaoConcluidas = new javax.swing.JList<>();
        jButtonAtualizarMissoesNaoConcluidas = new javax.swing.JButton();
        jLabelEmail = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane5.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("BEM VINDO");

        jLabel2.setText("NOME DA MISSÃO");

        jLabel3.setText("OBJETIVO DA MISSÃO");

        jLabel4.setText("MATERIAL DESEJADO");

        buttonGroup1.add(RadioMaterialBorracha);
        RadioMaterialBorracha.setText("BORRACHA");

        buttonGroup1.add(RadioMaterialVidro);
        RadioMaterialVidro.setText("VIDRO");

        buttonGroup1.add(RadioMaterialMetais);
        RadioMaterialMetais.setText("METAIS");
        RadioMaterialMetais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioMaterialMetaisActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadioMaterialMadeira);
        RadioMaterialMadeira.setText("MADEIRA");

        buttonGroup1.add(RadioMaterialPlastico);
        RadioMaterialPlastico.setText("PLASTICO");

        buttonGroup1.add(RadioMaterialPapel);
        RadioMaterialPapel.setText("PAPEL");

        TelaRecebedorNomeMissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelaRecebedorNomeMissaoActionPerformed(evt);
            }
        });

        TelaRecebedorMenuObjetivoMissao.setColumns(20);
        TelaRecebedorMenuObjetivoMissao.setRows(5);
        jScrollPane1.setViewportView(TelaRecebedorMenuObjetivoMissao);

        jLabel7.setText("QUANTIDADE DE MATERIAL (Kg)");

        jSpinnerQtdMaterial.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jSpinnerQtdMaterial.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerQtdMaterialStateChanged(evt);
            }
        });
        jSpinnerQtdMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSpinnerQtdMaterialMouseClicked(evt);
            }
        });

        jLabel5.setText("PONTUAÇÃO");

        TelaRecebedorPontuacaoMissaoCriada.setText("1");

        CadastrarMissao.setText("CADASTRAR");
        CadastrarMissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarMissaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TelaRecebedorNomeMissao, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RadioMaterialBorracha)
                    .addComponent(RadioMaterialMadeira))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RadioMaterialVidro)
                    .addComponent(RadioMaterialPlastico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RadioMaterialMetais)
                    .addComponent(RadioMaterialPapel))
                .addGap(60, 60, 60))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel7)
                .addGap(37, 37, 37)
                .addComponent(jSpinnerQtdMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(TelaRecebedorPontuacaoMissaoCriada, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(CadastrarMissao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TelaRecebedorNomeMissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioMaterialBorracha)
                    .addComponent(RadioMaterialVidro)
                    .addComponent(RadioMaterialMetais))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioMaterialMadeira)
                    .addComponent(RadioMaterialPlastico)
                    .addComponent(RadioMaterialPapel))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jSpinnerQtdMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TelaRecebedorPontuacaoMissaoCriada, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CadastrarMissao)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelCriarMissaoLayout = new javax.swing.GroupLayout(jPanelCriarMissao);
        jPanelCriarMissao.setLayout(jPanelCriarMissaoLayout);
        jPanelCriarMissaoLayout.setHorizontalGroup(
            jPanelCriarMissaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCriarMissaoLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanelCriarMissaoLayout.setVerticalGroup(
            jPanelCriarMissaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCriarMissaoLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        TelaRecebedorMenuMissao.addTab("CRIAR ", jPanelCriarMissao);

        jScrollPane3.setViewportView(ListaDeMissaoEmAberto);

        jButtonAtualizarListaEmAberto.setText("ATUALIZAR");
        jButtonAtualizarListaEmAberto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarListaEmAbertoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jButtonAtualizarListaEmAberto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAtualizarListaEmAberto)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelEmAbertoLayout = new javax.swing.GroupLayout(jPanelEmAberto);
        jPanelEmAberto.setLayout(jPanelEmAbertoLayout);
        jPanelEmAbertoLayout.setHorizontalGroup(
            jPanelEmAbertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelEmAbertoLayout.setVerticalGroup(
            jPanelEmAbertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmAbertoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        TelaRecebedorMenuMissao.addTab("EM ABERTO", jPanelEmAberto);

        jScrollPane2.setViewportView(TelaRecebedorMissoesEmAndamento);

        jLabel6.setText("SUAS MISSÕES");

        BotaoConcluirMissaoEmAndamento.setText("MISSÃO CONCLUIDA");
        BotaoConcluirMissaoEmAndamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoConcluirMissaoEmAndamentoActionPerformed(evt);
            }
        });

        BotaoMissaoNaoConcluida.setText("MISSÃO NÃO CONCLUIDA");
        BotaoMissaoNaoConcluida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoMissaoNaoConcluidaActionPerformed(evt);
            }
        });

        jButtonAtualizarListaEmAndamento.setText("ATUALIZAR");
        jButtonAtualizarListaEmAndamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarListaEmAndamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEmAndamentoLayout = new javax.swing.GroupLayout(jPanelEmAndamento);
        jPanelEmAndamento.setLayout(jPanelEmAndamentoLayout);
        jPanelEmAndamentoLayout.setHorizontalGroup(
            jPanelEmAndamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmAndamentoLayout.createSequentialGroup()
                .addGroup(jPanelEmAndamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEmAndamentoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelEmAndamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanelEmAndamentoLayout.createSequentialGroup()
                                .addComponent(BotaoConcluirMissaoEmAndamento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                                .addComponent(BotaoMissaoNaoConcluida))))
                    .addGroup(jPanelEmAndamentoLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAtualizarListaEmAndamento)))
                .addContainerGap())
        );
        jPanelEmAndamentoLayout.setVerticalGroup(
            jPanelEmAndamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEmAndamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEmAndamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAtualizarListaEmAndamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelEmAndamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoConcluirMissaoEmAndamento)
                    .addComponent(BotaoMissaoNaoConcluida))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEmAndamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEmAndamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TelaRecebedorMenuMissao.addTab("EM ANDAMENTIO", jPanel3);

        jScrollPane4.setViewportView(ListaMissoesConcluidas);

        jButtonAtualizarListaMissoesConcluidas.setText("ATUALIZAR");
        jButtonAtualizarListaMissoesConcluidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarListaMissoesConcluidasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelConcluidaLayout = new javax.swing.GroupLayout(jPanelConcluida);
        jPanelConcluida.setLayout(jPanelConcluidaLayout);
        jPanelConcluidaLayout.setHorizontalGroup(
            jPanelConcluidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConcluidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConcluidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6)
                    .addComponent(jSeparator5)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanelConcluidaLayout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(jButtonAtualizarListaMissoesConcluidas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelConcluidaLayout.setVerticalGroup(
            jPanelConcluidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConcluidaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAtualizarListaMissoesConcluidas)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelConcluida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelConcluida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TelaRecebedorMenuMissao.addTab("CONCLUIDAS", jPanel8);

        jScrollPane6.setViewportView(jListMissoesNaoConcluidas);

        jButtonAtualizarMissoesNaoConcluidas.setText("ATUALIZAR");
        jButtonAtualizarMissoesNaoConcluidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarMissoesNaoConcluidasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jButtonAtualizarMissoesNaoConcluidas)
                .addContainerGap(200, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAtualizarMissoesNaoConcluidas)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        TelaRecebedorMenuMissao.addTab("NÃO CONCLUIDAS", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(133, 133, 133))
                    .addComponent(jSeparator1))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TelaRecebedorMenuMissao)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TelaRecebedorMenuMissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarMissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarMissaoActionPerformed
       
      int peso = 0;
     
      int qtdMaterial;
        

        int pontuacao;

        Missao m = new Missao();
        MissaoDao md = new MissaoDao();
        Status s = new Status();
        Material ma = new Material();
        LoginModel loginModel;

        m.setNome(TelaRecebedorNomeMissao.getText());

        m.setObjetivo(TelaRecebedorMenuObjetivoMissao.getText());

        if (RadioMaterialBorracha.isSelected()) {
            ma.setTipoDoMaterial(1);//material borracha id=1,
            peso = 5;
        }
        if (RadioMaterialMadeira.isSelected()) {
            ma.setTipoDoMaterial(2);//material madeira id=2,
            peso = 3;
        }
        if (RadioMaterialMetais.isSelected()) {
            ma.setTipoDoMaterial(3);//material metais id=3,
            peso = 6;
        }
        if (RadioMaterialPapel.isSelected()) {
            ma.setTipoDoMaterial(4);//material papel id=4,
            peso = 1;
        }
        if (RadioMaterialPlastico.isSelected()) {
            ma.setTipoDoMaterial(5);//material Plastico id=5,
            peso = 2;
        }
        if (RadioMaterialVidro.isSelected()) {
            ma.setTipoDoMaterial(6);//material vidro id=6,
            peso = 4;
        }

        m.setMaterial(ma);
        
        System.out.println(jLabelEmail.getText() + " tela do fornecedor");

       m.setEmailDoCriador(jLabelEmail.getText());

        m.setEmailDoFornecedor(null);
        
        
       qtdMaterial =  (Integer) jSpinnerQtdMaterial.getValue();
       
      
       
        
        //jSpinnerQuantidadeMaterial.setEditor(create);
        
        //qtdMaterial = );
        
        
        
        System.out.println(qtdMaterial);
        
        pontuacao = m.calcularPontuacao(peso, qtdMaterial);
        System.out.println(pontuacao);

        m.setPontuacao(pontuacao);

        s.setStatus(0);

        m.setStatus(s);

        md.cadastrarMissao(m);


    }//GEN-LAST:event_CadastrarMissaoActionPerformed

    private void TelaRecebedorNomeMissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelaRecebedorNomeMissaoActionPerformed

    }//GEN-LAST:event_TelaRecebedorNomeMissaoActionPerformed

    private void jSpinnerQtdMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSpinnerQtdMaterialMouseClicked
      
    }//GEN-LAST:event_jSpinnerQtdMaterialMouseClicked

    private void jSpinnerQtdMaterialStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerQtdMaterialStateChanged
        int peso = 0;
     
      int qtdMaterial;
        
        Missao m = new Missao();
         
         if (RadioMaterialBorracha.isSelected()) {
          //  ma.setTipoDoMaterial(1);//material borracha id=1,
            peso = 5;
        }
        if (RadioMaterialMadeira.isSelected()) {
          //  ma.setTipoDoMaterial(2);//material madeira id=2,
            peso = 3;
        }
        if (RadioMaterialMetais.isSelected()) {
          //  ma.setTipoDoMaterial(3);//material metais id=3,
            peso = 6;
        }
        if (RadioMaterialPapel.isSelected()) {
          //  ma.setTipoDoMaterial(4);//material papel id=4,
            peso = 1;
        }
        if (RadioMaterialPlastico.isSelected()) {
            //ma.setTipoDoMaterial(5);//material Plastico id=5,
            peso = 2;
        }
        if (RadioMaterialVidro.isSelected()) {
           // ma.setTipoDoMaterial(6);//material vidro id=6,
            peso = 4;
        }
        
        
       qtdMaterial =  (Integer) jSpinnerQtdMaterial.getValue();
         
         
       TelaRecebedorPontuacaoMissaoCriada.setText( Integer.toString(m.calcularPontuacao(peso, qtdMaterial)) ); 
       
       
    }//GEN-LAST:event_jSpinnerQtdMaterialStateChanged

    private void RadioMaterialMetaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioMaterialMetaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioMaterialMetaisActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      
        DefaultListModel modelo1 = new DefaultListModel();
        DefaultListModel modelo2 = new DefaultListModel();
        DefaultListModel modelo3 = new DefaultListModel();
        DefaultListModel modelo4 = new DefaultListModel();
        
        TelaRecebedorMissoesEmAndamento.setModel(modelo1);
        ListaDeMissaoEmAberto.setModel(modelo2);
        ListaMissoesConcluidas.setModel(modelo3);
        jListMissoesNaoConcluidas.setModel(modelo4);
        
        String email = jLabelEmail.getText();
        
       
        
        MissaoDao mdao = new MissaoDao();
        
        for(Missao m: mdao.listarMissoesPorUsuarioRecebedor(1, email)){
        
        
        modelo1.addElement("(id: " + m.getId() + ")"  + " (nome da missão: " + m.getNome() + ") " + "(pontução"  + m.getPontuacao() + ")" + "(email de quem aceitou a missão: " + m.getEmailDoFornecedor() + ")");
        }
        
         for(Missao m: mdao.listarMissoesPorUsuarioRecebedor(0, email)){
        
        
        modelo2.addElement("(id: " + m.getId() + ")"  + " (nome da missão: " + m.getNome() + ") " + "(pontução"  + m.getPontuacao() + ")");
        }
         
        for(Missao m: mdao.listarMissoesPorUsuarioRecebedor(2, email)){
        
        
        modelo3.addElement("(id: " + m.getId() + ")"  + " (nome da missão: " + m.getNome() + ") " + "(pontução"  + m.getPontuacao() + ")" + "(email de quem aceitou a missão: " + m.getEmailDoFornecedor() + ")");
        }
        
        for(Missao m: mdao.listarMissoesPorUsuarioRecebedor(3, email)){
        
        
        modelo4.addElement("(id: " + m.getId() + ")"  + " (nome da missão: " + m.getNome() + ") " + "(pontução"  + m.getPontuacao() + ")" + "(email de quem aceitou a missão: " + m.getEmailDoFornecedor() + ")");
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void BotaoConcluirMissaoEmAndamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoConcluirMissaoEmAndamentoActionPerformed
       
       String email = jLabelEmail.getText();
       int idMissao;
       int valorMissao;
       MissaoDao mdao = new MissaoDao();
       UsuarioFornecedorDAO ufdao = new UsuarioFornecedorDAO();
       
       int i = TelaRecebedorMissoesEmAndamento.getSelectedIndex();
       
       
     idMissao =  mdao.listarMissoesPorUsuarioRecebedor(1, email).get(i).getId();
     String emailDoFornecedor = mdao.listarMissoesPorUsuarioRecebedor(1, email).get(i).getEmailDoFornecedor();
     
        System.out.println(idMissao);
        System.out.println(emailDoFornecedor);
        System.out.println("email logado " + email);
        
      
       
      
      valorMissao = mdao.valorDaMissaoAceita(emailDoFornecedor, idMissao);
      ufdao.atualizarPontuacao(emailDoFornecedor, valorMissao);
      mdao.missaoConcluidaSucesso(idMissao);
      
      DefaultListModel modelo = new DefaultListModel();
        
        TelaRecebedorMissoesEmAndamento.setModel(modelo);
        
        //String email = jLabelEmail.getText();
        System.out.println("email logado bnt atualizar " + email);
        
       
        
        //MissaoDao mdao = new MissaoDao();
        
        for(Missao m: mdao.listarMissoesPorUsuarioRecebedor(1, email)){
        
        
        modelo.addElement("(id: " + m.getId() + ")"  + " (nome da missão: " + m.getNome() + ") " + "(pontução"  + m.getPontuacao() + ")" + "(email de quem aceitou a missão: " + m.getEmailDoFornecedor() + ")");
        
            System.out.println(m.getNome());
        }
      
      
    }//GEN-LAST:event_BotaoConcluirMissaoEmAndamentoActionPerformed

    private void BotaoMissaoNaoConcluidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoMissaoNaoConcluidaActionPerformed
       String email = jLabelEmail.getText();
       int idMissao;
       int valorMissao;
       MissaoDao mdao = new MissaoDao();
       UsuarioFornecedorDAO ufdao = new UsuarioFornecedorDAO();
       
       int i = TelaRecebedorMissoesEmAndamento.getSelectedIndex();
       
       
     idMissao =  mdao.listarMissoesPorUsuarioRecebedor(1, email).get(i).getId();
     String emailDoFornecedor = mdao.listarMissoesPorUsuarioRecebedor(1, email).get(i).getEmailDoFornecedor();
     
        System.out.println(idMissao);
        System.out.println(emailDoFornecedor);
        System.out.println("email logado " + email);
        
      
       
     
      valorMissao = mdao.valorDaMissaoAceita(emailDoFornecedor, idMissao);
      System.out.println(valorMissao);
      ufdao.atualizarPontuacaoSemSucesso(emailDoFornecedor, valorMissao);
      mdao.missaoConcluidaSemSucesso(idMissao);
      
      DefaultListModel modelo = new DefaultListModel();
        
        TelaRecebedorMissoesEmAndamento.setModel(modelo);
        
        //String email = jLabelEmail.getText();
        System.out.println("email logado bnt atualizar " + email);
        
       
        
        //MissaoDao mdao = new MissaoDao();
        
        for(Missao m: mdao.listarMissoesPorUsuarioRecebedor(1, email)){
        
        
        modelo.addElement("(id: " + m.getId() + ")"  + " (nome da missão: " + m.getNome() + ") " + "(pontução"  + m.getPontuacao() + ")" + "(email de quem aceitou a missão: " + m.getEmailDoFornecedor() + ")");
        
            System.out.println(m.getNome());
        }
      
    }//GEN-LAST:event_BotaoMissaoNaoConcluidaActionPerformed

    private void jButtonAtualizarListaMissoesConcluidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarListaMissoesConcluidasActionPerformed
        DefaultListModel modelo = new DefaultListModel();
        
        ListaMissoesConcluidas.setModel(modelo);
        
        String email = jLabelEmail.getText();
        System.out.println("email logado bnt atualizar " + email);
        
       
        
        MissaoDao mdao = new MissaoDao();
        
        for(Missao m: mdao.listarMissoesPorUsuarioRecebedor(2, email)){
        
        
        modelo.addElement("(id: " + m.getId() + ")"  + " (nome da missão: " + m.getNome() + ") " + "(pontução"  + m.getPontuacao() + ")" + "(email de quem aceitou a missão: " + m.getEmailDoFornecedor() + ")");
        
            System.out.println(m.getNome());
        }
    }//GEN-LAST:event_jButtonAtualizarListaMissoesConcluidasActionPerformed

    private void jButtonAtualizarListaEmAbertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarListaEmAbertoActionPerformed
        DefaultListModel modelo = new DefaultListModel();
        
         MissaoDao mdao = new MissaoDao();
        
        
         ListaDeMissaoEmAberto.setModel(modelo);
        
        String email = jLabelEmail.getText();
        System.out.println("email logado bnt atualizar " + email);
        
       
        
       
        
        for(Missao m: mdao.listarMissoesPorUsuarioRecebedor(0, email)){
        
        
        modelo.addElement("(id: " + m.getId() + ")"  + " (nome da missão: " + m.getNome() + ") " + "(pontução"  + m.getPontuacao() + ")");
        
            System.out.println(m.getNome());
        }
      
    }//GEN-LAST:event_jButtonAtualizarListaEmAbertoActionPerformed

    private void jButtonAtualizarMissoesNaoConcluidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarMissoesNaoConcluidasActionPerformed
         DefaultListModel modelo = new DefaultListModel();
        
        jListMissoesNaoConcluidas.setModel(modelo);
        
        String email = jLabelEmail.getText();
        System.out.println("email logado bnt atualizar " + email);
        
       
        
        MissaoDao mdao = new MissaoDao();
        
        for(Missao m: mdao.listarMissoesPorUsuarioRecebedor(3, email)){
        
        
        modelo.addElement("(id: " + m.getId() + ")"  + " (nome da missão: " + m.getNome() + ") " + "(pontução"  + m.getPontuacao() + ")" + "(email de quem aceitou a missão: " + m.getEmailDoFornecedor() + ")");
        
            System.out.println(m.getNome());
        }
    }//GEN-LAST:event_jButtonAtualizarMissoesNaoConcluidasActionPerformed

    private void jButtonAtualizarListaEmAndamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarListaEmAndamentoActionPerformed
        DefaultListModel modelo = new DefaultListModel();
        
        TelaRecebedorMissoesEmAndamento.setModel(modelo);
        
        String email = jLabelEmail.getText();
        System.out.println("email logado bnt atualizar " + email);
        
       
        
        MissaoDao mdao = new MissaoDao();
        
        for(Missao m: mdao.listarMissoesPorUsuarioRecebedor(1, email)){
        
        
        modelo.addElement("(id: " + m.getId() + ")"  + " (nome da missão: " + m.getNome() + ") " + "(pontução"  + m.getPontuacao() + ")" + "(email de quem aceitou a missão: " + m.getEmailDoFornecedor() + ")");
        
            System.out.println(m.getNome());
        }
    }//GEN-LAST:event_jButtonAtualizarListaEmAndamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarioRecebedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarioRecebedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarioRecebedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarioRecebedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUsuarioRecebedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoConcluirMissaoEmAndamento;
    private javax.swing.JButton BotaoMissaoNaoConcluida;
    private javax.swing.JToggleButton CadastrarMissao;
    private javax.swing.JList<String> ListaDeMissaoEmAberto;
    private javax.swing.JList<String> ListaMissoesConcluidas;
    private javax.swing.JRadioButton RadioMaterialBorracha;
    private javax.swing.JRadioButton RadioMaterialMadeira;
    private javax.swing.JRadioButton RadioMaterialMetais;
    private javax.swing.JRadioButton RadioMaterialPapel;
    private javax.swing.JRadioButton RadioMaterialPlastico;
    private javax.swing.JRadioButton RadioMaterialVidro;
    private javax.swing.JTabbedPane TelaRecebedorMenuMissao;
    private javax.swing.JTextArea TelaRecebedorMenuObjetivoMissao;
    private javax.swing.JList<String> TelaRecebedorMissoesEmAndamento;
    private javax.swing.JTextField TelaRecebedorNomeMissao;
    private javax.swing.JLabel TelaRecebedorPontuacaoMissaoCriada;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAtualizarListaEmAberto;
    private javax.swing.JButton jButtonAtualizarListaEmAndamento;
    private javax.swing.JButton jButtonAtualizarListaMissoesConcluidas;
    private javax.swing.JButton jButtonAtualizarMissoesNaoConcluidas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JList<String> jListMissoesNaoConcluidas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelConcluida;
    private javax.swing.JPanel jPanelCriarMissao;
    private javax.swing.JPanel jPanelEmAberto;
    private javax.swing.JPanel jPanelEmAndamento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSpinner jSpinnerQtdMaterial;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
